### ISSUE TITLE
Cofh Crash

### ISSUE THREAD

**Issue by kurokuno** [squeek502/VeganOption#7] opened 2015-01-26 01:03 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 26/01/15 11:58 AM
Description: Initializing game

java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class cofh.lib.util.ItemWrapper id= 528696606 hashCode= 362151936 toString= cofh.lib.util.ItemWrapper@528696606{m:0, i:net.minecraft.item.ItemSeedFood@2093530430, v:5526}; object #2 =class cofh.lib.util.ItemWrapper id= 1664009403 hashCode= 362151936 toString= cofh.lib.util.ItemWrapper@1664009403{m:0, i:net.minecraft.item.ItemSeedFood@2093530430, v:5526}

hashCode() and/or equals() have inconsistent implementation
Key set lost entries, now got 1598 instead of 1602. This can manifest itself as an apparent duplicate key.
    at gnu.trove.impl.hash.TObjectHash.buildObjectContractViolation(TObjectHash.java:464)
    at gnu.trove.impl.hash.TObjectHash.throwObjectContractViolation(TObjectHash.java:448)
    at gnu.trove.map.hash.THashMap.rehash(THashMap.java:403)
    at gnu.trove.impl.hash.THash.postInsertHook(THash.java:388)
    at gnu.trove.map.hash.THashMap.doPut(THashMap.java:178)
    at gnu.trove.map.hash.THashMap.put(THashMap.java:145)
    at cofh.core.util.oredict.OreDictionaryArbiter.registerOreDictionaryEntry(OreDictionaryArbiter.java:93)
    at cofh.core.Proxy.handleOreRegisterEvent(Proxy.java:51)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_42_Proxy_handleOreRegisterEvent_OreRegisterEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:472)
    at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:432)
    at squeek.veganoption.content.modules.Composting.recipes(Composting.java:92)
    at squeek.veganoption.content.ContentModuleHandler.init(ContentModuleHandler.java:65)
    at squeek.veganoption.VeganOption.init(VeganOption.java:43)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by squeek502** [comment] 2015-01-26 02:08
What version of the CoFH mods are you using? Can I get a full mod list?

**Comment by kurokuno** [comment] 2015-01-26 02:25
you can indeed

forge 1291

ProjectRed-1.7.10-4.5.8.59-Integration.jar
ProjectRed-1.7.10-4.5.8.59-Lighting.jar
ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar
ProjectRed-1.7.10-4.5.8.59-World.jar
Railcraft_1.7.10-9.4.0.0.jar
RandomThings-2.2.4.jar
RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar
RenderPlayerAPI-1.7.10-1.0.jar
resonant-engine-3.3.0.389-core.jar
ShadersModCore-v2.3.28-mc1.7.10-f.jar
SimplyJetpacks-MC1.7.10-1.3.2(1).jar
slick-util.jar
SmartCore-1.7.10-1.0.jar
SmartMoving-1.7.10-15.2.jar
SmartRender-1.7.10-2.0.jar
SolarFlux-1.7.10-0.5a.jar
StevesAddons-1.7.10-0.6.8.jar
StevesFactoryManagerA93.jar
Tails-1.7.10-1.2.3.jar
TConstruct-1.7.10-1.8.2a.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-13.jar
TiCTooltips-mc1.7.10-1.1.11b.jar
TMechworks-1.7.10-0.2.10.jar
Torcherino-1.7.10-1.8s.jar
TorchTools-1.7.10-1.1.0.21.jar
Translocator-1.7.10-1.1.1.14-universal.jar
TrussMod-beta-1.7.10-37.jar
twilightforest-1.7.10-2.3.2.jar
VillageTaverns-2.2.1-0.23.jar
VoidWorld.jar
Waila-1.5.8a_1.7.10.jar
Wawla-1.1.0_1.7.10.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
[1.7.2] EnderBook v2.1.2.6.jar
[1.7.2+] KingCore v3.4.2.19.jar
ae2stuff-mc1710-0.1.1.5.jar
appliedenergistics2-rv2-beta-7.jar
Baubles-1.7.10-1.0.1.8.jar
bdlib-mc1710-1.5.1.32.jar
BiblioCraft[v1.9.1][MC1.7.10].jar
BigReactors-0.4.0A.jar
binnie-mods-2.0-pre4.jar
BloodMagic-1.7.10-1.3.0b-3.jar
Botania r1.3-152.jar
buildcraft-6.3.3.jar
Carpenter's Blocks v3.3.4.2 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.17-universal.jar
Chisel2_DEV-2.3.2.221de9d.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
CoFHCore-[1.7.10]3.0.0B9-40.jar
CoFHLib-[1.7.10]1.0.0B8-34.jar
compactmachines-1.7.10-1.15.jar
ComputerCraft1.65.jar
CosmeticArmor-1.7.10-1.0.5.B8-universal.jar
D3Core-1.7.10-1.1.0.19.jar
denseores-1.5.jar
Draconic-Evolution-1.7.10-v1.0.0e.jar
EasyCrafting-1.7.10-2.0.1.16.jar
EnderIO-1.7.10-2.2.7.329.jar
EnderStorage-1.7.10-1.4.5.27-universal.jar
EnderTech-1.7.10-0.3.0.358.jar
enderutilities-1.7.10-0.3.5.1.jar
EnderZoo-1.7.10-1.0.7.16.jar
EnndsCore-2.1.1.109-b.jar
ExtraCells-1.7.10-2.2.46b72.jar
ExtraTiC-1.7.10-1.0.3.jar
extrautilities-1.2.1.jar
fastcraft-1.16.jar
FoodPlus-1.7.2-3.2rS.jar
forestry_1.7.10-3.3.0.6.jar
FoxLib-1.7.10-0.6.0.jar
GreenThumb-1.7.10-1.1.0.8.jar
ibench-1.7.10-1.0.12.jar
IGW-Mod.jar
InventoryTweaks-1.58-147.jar
Iron Backpacks-1.7.10-0.9.7-1-universal.jar
ironchest-1.7.10-6.0.62.742-universal.jar
ironfist-1.3.jar
Jabba-1.2.0a_1.7.10.jar
JourneyMap5.0.1_Unlimited_MC1.7.10.jar
Liquipacks-1.7.10-1.3.2.jar
logisticspipes-0.8.3.92.jar
malisiscore-1.7.10-0.10.5.jar
malisisdoors-1.7.10-1.4.3.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-7.1.2.157.jar
MekanismGenerators-1.7.10-7.1.2.157.jar
MekanismTools-1.7.10-7.1.2.157.jar
Metallurgy-1.7.10-4.0.5.75.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
meteors-1.7.10-2.14.jar
mffs-4.1.1.61-core.jar
MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar
MineTweaker3-1.7.10-3.0.9C.jar
MineTweakerRecipeMaker-1.7.10-1.1.0.15.jar
MmmMmmMmmMmm-1.6.jar
MobiusCore-1.2.3_1.7.10.jar
ModularPowersuitAddons-0.11.0.5-QMX.jar
ModularPowersuits-0.11.0.5-QMX.jar
neiaddons-mc1710-1.12.2.9.jar
NEIIntegration-MC1.7.10-1.0.3.jar
NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar
NetherOres-[1.7.10]2.3.0RC4-4.jar
nhwrench2-1.7.10-2.0.1.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
NotEnoughKeys-1.7.10-1.0.0b29.jar
Numina-0.4.0.5-QMX.jar
OggAudioData.jar
OpenBlocks-1.7.10-1.3-snapshot-542.jar
OpenModsLib-1.7.10-0.6-snapshot-289.jar
OpenModularTurrets-1.7.10-1.3.2-24.jar
OpenPeripheralAddons-1.7.10-0.2.0-snapshot-145.jar
OpenPeripheralCore-1.7.10-0.5.0-snapshot-180.jar
OpenPeripheralIntegration-1.7.10-0.1.0-snapshot-25.jar
Opis-1.2.3_1.7.10.jar
OptiFine_1.7.10_HD_U_B1.jar
PlanetguyLib-1.2.jar
PlayerAPI-1.7.10-1.1.jar
PneumaticCraft-1.7.10-1.5.3-universal.jar
ProgressiveAutomation-1.7.10-1.5.6.jar
ProjectRed-1.7.10-4.5.8.59-Base.jar
ProjectRed-1.7.10-4.5.8.59-Compat.jar

**Comment by squeek502** [comment] 2015-01-26 02:38
Forge version? I can't seem to reproduce this with only the following mods installed:
- CoFHCore-[1.7.10]3.0.0B9-40
- ThermalExpansion-[1.7.10]4.0.0B8-23
- ThermalFoundation-[1.7.10]1.0.0RC1-13
- VeganOption-mc1.7.10-0.1.0

**Comment by squeek502** [comment] 2015-01-27 10:20
Still not able to reproduce this, but it may have been inadvertently fixed by 9c22917d9699ff9f5ef2fa35273878cd32f91b24

Can you try this build and see if you still crash?
[VeganOption-mc1.7.10-0.1.0-test.jar](http://www.ryanliptak.com/misc/VeganOption-mc1.7.10-0.1.0-test.jar)

**Comment by squeek502** [comment] 2015-01-28 22:23
@kurokuno?

**Comment by kurokuno** [comment] 2015-01-31 03:32
sorry been away for a bit will test today and get back to you

**Comment by kurokuno** [comment] 2015-01-31 09:44
ok so works just fine thanks <3

**Comment by squeek502** [comment] 2015-01-31 09:55
Very strange. Thanks for reporting/testing it, though.

**Closed as completed by squeek502** 2015-01-31 09:55 UTC
