### ISSUE TITLE
Vegan Option triggering a weird crafting bug in forge that affects other mods (Extra Utilities, RF Tools)

### ISSUE THREAD

**Issue by BBoldt** [squeek502/VeganOption#22] opened 2015-07-16 08:01 UTC
This may be hard for me to explain, so I will just refer you to these issues explaining it.
https://github.com/rwtema/extrautilities/issues/525
https://github.com/McJty/RFTools/issues/91

The other known mod that caused this issue was Rotarycraft/DragonAPI, and it has since been fixed in that mod.

https://github.com/rwtema/extrautilities/issues/525#issuecomment-120330125

Also what led me to discover it was your mod causing this, was a player of my modpack pointed out this line in the log:

`[16/7/2015 03:02:38 AM] [Client thread/INFO] [VeganOption]: Replaced 839 recipes with OreDictionary'd equivalents (took 0.165 seconds)`

After removing vegan option, the specific crafting recipes in extra utils and rf tools were fixed.
- Forge 1481
- VeganOption-mc1.7.10-0.1.1
- extrautilities-1.2.8
- rftools-3.11

**Comment by TomeWyrm** [comment] 2015-07-16 12:49
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/73#issuecomment-119742796

As well as the next two comments are what you're looking for. Double-check that you aren't triggering the ore dictionary later in the initialization steps than you need to and you should be able to fix the bug.

**Comment by squeek502** [comment] 2015-07-16 15:30
Thanks for the links. Might be a hard one to fix as this mod heavily relies on modifying recipes, and it's hard to rely on any mod to register recipes/oredict entries at the "proper" stage (the only thing you can count on is that all mods do it in different stages).

Will look into it.

**Comment by squeek502** [comment] 2015-07-20 03:01
Unable to replicate the Extra Utilities bug but I found the cause of the RFTools one. RFTools is using an extended `ShapedRecipes` class for its Module recipes, and I'm clobbering it by replacing it with ShapedOreRecipe (because VO currently assumes everything that extends from ShapedRecipes is a plain ShapedRecipes instance). Whoops.

Will look into it more and decide on the best way to fix it.

**Comment by squeek502** [comment] 2015-08-21 05:38
Should be fixed in https://github.com/squeek502/VeganOption/releases/tag/v0.1.2

**Closed as completed** 2015-08-21 05:37 UTC
Labels: bug, confirmed
